import sys
import os
import numpy as np
import warnings
warnings.filterwarnings("ignore")

from google.adk.agents.llm_agent import Agent
from google.adk.agents.sequential_agent import SequentialAgent
from google.adk.agents.loop_agent import LoopAgent
from google.adk.tools.tool_context import ToolContext
from google.genai import types
from google.adk.planners import BuiltInPlanner
from google.adk.sessions import InMemorySessionService
from google.adk.runners import Runner
from pydantic import BaseModel, Field
from .prompts import query_analysis_prompt, section_generation_prompt, website_generation_prompt


# define the output schema for the query analysis agent
class QueryAnalysisOutput(BaseModel):
    query: str = Field(description="The user query.")
    sections: list[str] = Field(description="The sections of the website content.")
    formatting_instructions: list[str] = Field(description="The formatting instructions for the section generation agent.")


def exit_loop(tool_context: ToolContext):
  """Call this function ONLY when the required number of sections was generated"""
  print(f"  [Tool Call] exit_loop triggered by {tool_context.agent_name}")
  tool_context.actions.escalate = True
  # Return empty dict as tools should typically return JSON-serializable output
  return {}


# agent that will generate sections for website content
section_generation_agent = Agent(
    model='gemini-2.5-flash',
    name='section_generation_agent',
    description='Agent that generates sections for website content based on the user query',
    instruction=section_generation_prompt,
    output_key='sections',
    tools=[exit_loop]
)


section_loop_agent = LoopAgent(
    name='section_loop_agent',
    sub_agents=[section_generation_agent],
    max_iterations=10 
)


query_analysis_agent = Agent(
    model='gemini-2.5-flash',
    name='query_analysis_agent',
    description='Agent that analyzes user queries outputs the instruction for section generation agent in JSON format',
    instruction=query_analysis_prompt,
    output_key='query_analysis',
    output_schema=QueryAnalysisOutput,
    generate_content_config=types.GenerateContentConfig(
        temperature=0.8, 
        max_output_tokens=2000,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.BLOCK_LOW_AND_ABOVE,
            )
        ]
    )
)


website_generation_agent = Agent(
    model='gemini-2.5-flash',
    name='website_generation_agent',
    description='Agent that generates website content based on the sections generated by section generation agent',
    instruction=website_generation_prompt,
    output_key='website_content'
)


root_agent = SequentialAgent(
    name='root_agent',
    description='A helpful assistant for user questions that generates website content based on user queries by analyzing the query, generating sections, and creating the final website content.',
    sub_agents=[query_analysis_agent, section_loop_agent, website_generation_agent]
)